# MKAC мейн конфиг
# Copyright 2026 korpys667, MillyOfficial, Licensed under GPLv3.

# Локализация: en, ru
locale: "ru"

ai:
  # Включить AI Check?
  enabled: false
  # Ссылка на API для AI.
  server: "https://mkac.fun/api/"
  # Тут API ключ для AI сервера.
  api-key: "MKAC"
  # Количество тиков, которые надо отправить в последовательности AI.
  sequence: 40
  #
  #Количество тиков, которое нужно подождать перед отправкой следующей последовательности.
  step: 20
  buffer:
    # Уровень нарушения (VL), при котором будет флаг.
    flag: 50.0
    # Значение, до которого сбрасывается буфер после флага.
    reset-on-flag: 25.0
    # Множитель для увеличения буфера при высокой вероятности читерства (>0,9).
    # (probability - 0.9) * multiplier
    multiplier: 100.0
    # Сумма, вычитаемая из буфера при низкой вероятности читерства (<0,1).
    decrease: 0.25
  damage-reduction:
    # Включить урезание урона?
    enabled: true
    # Вероятность для начала урезания.
    prob: 0.9
    # Множители дамага
    # 0.1: с вероятностью 100% (1.0) урон будет снижен на 10%.
    # 1.0: с вероятностью 100% (1.0) урон будет снижен на 100%.
    # 2.0: с вероятностью 95% (0,95) урон будет снижен на 100%.
    multiplier: 1.0
  worldguard:
    # Включить проверку региона WorldGuard?
    enabled: true
    # Список регионов WorldGuard, где проверка ИИ отключена.
    disabled-regions:
      - "spawn:spawn"

client-brand:
  # Это означает, что версия не будет отображаться админам, если она соответствует следующим версиям.
  ignored-clients:
    - "^vanilla$"
    - "^fabric$"
    - "^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4}$"
    - "^Feather Fabric$"
    - "^labymod$"
  # MKAC внесет в черный список определенные версии Forge, содержащие встроенные читы для Reach (Forge 1.18.2–1.19.3).
  # Установка этого параметра в значение false позволит указанным клиентам подключаться к серверу. Отключайте эту функцию на свой страх и риск.
  disconnect-blacklisted-forge-versions: true

alerts:
  print-to-console: true

history:
  enabled: true

suspicious:
  alerts:
    buffer: 25.0

debug:
  # AI_PROBABILITY, AI_TIMEOUT, WORLDGUARD, PACKET_DUPLICATION
  enabled-categories: []
